import pandas as pd
msgs = pd.read_csv('dataset/messages.csv')
imgs = pd.read_csv('dataset/images.csv')
reqs = pd.read_csv('dataset/requests.csv')
msg_count = msgs['request_id'].nunique()
img_count = imgs['request_id'].nunique()
total = len(reqs)
neither = total - len(set(msgs['request_id']) | set(imgs['request_id']))
print(f'Total requests: {total}')
print(f'With messages: {msg_count}')
print(f'With images: {img_count}')
print(f'With neither: {neither}')
print(f'Total messages: {len(msgs)}')
print(f'Total images: {len(imgs)}')
